# 开发环境
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://192.168.38.131:3306/foodie?characterEncoding=UTF-8&useSSL=false
    password: root
  redis:
    database: 0
    host: 192.168.38.131
    password: root
    port: 6379

mybatis:
  configuration:
    # 开发环境下打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
